pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                echo 'Build Successful'
            }
        }

       stage('Docker Build') {
    steps {
        bat '''
        docker build -f "Dockerfile" -t video-surveillance:v4 "Real-Time Video-Based Surveillance Detection System Using Deep Learning for Security Applications"
        '''
    }
}
    }
}
