pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                echo 'Build Successful'
            }
        }

        stage('Docker Build') {
            steps {
                bat '''
                cd "Real-Time Video-Based Surveillance Detection System Using Deep Learning for Security Applications"
                docker build -t video-surveillance:v4 .
                '''
            }
        }
    }
}
